apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-k8store
  namespace: keycloak
rules:
  - apiGroups: ["keycloak.k8store.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-k8store
  namespace: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-k8store
subjects:
  - kind: ServiceAccount
    name: keycloak
    namespace: keycloak
